package com.neutrinos.manulife;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CaseData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Client Id")
	private java.lang.String clientId;
	@org.kie.api.definition.type.Label("Role")
	private java.lang.String role;
	@org.kie.api.definition.type.Label("Sum Assured")
	private java.lang.Double sumAssured;
	@org.kie.api.definition.type.Label("Application Number")
	private java.lang.String applicationNo;
	@org.kie.api.definition.type.Label("Priority")
	private java.lang.Integer priority;

	private java.lang.Long proceessInstanceId;

	private java.lang.String mongoDocID;

	private java.lang.String product;

	private java.lang.String agentId;

	private java.lang.Integer coem;

	private java.lang.String coExcl;

	private java.lang.Integer level;

	private java.lang.String lastUser;

	private java.lang.String finfoId;

	private java.lang.Double premium;

	@org.kie.api.definition.type.Label("Decision")
	private java.lang.String decision;

	private java.lang.Integer count;

	private java.lang.String channel;

	public CaseData() {
	}

	public java.lang.String getClientId() {
		return this.clientId;
	}

	public void setClientId(java.lang.String clientId) {
		this.clientId = clientId;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.Double getSumAssured() {
		return this.sumAssured;
	}

	public void setSumAssured(java.lang.Double sumAssured) {
		this.sumAssured = sumAssured;
	}

	public java.lang.String getApplicationNo() {
		return this.applicationNo;
	}

	public void setApplicationNo(java.lang.String applicationNo) {
		this.applicationNo = applicationNo;
	}

	public java.lang.Integer getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Integer priority) {
		this.priority = priority;
	}

	public java.lang.Long getProceessInstanceId() {
		return this.proceessInstanceId;
	}

	public void setProceessInstanceId(java.lang.Long proceessInstanceId) {
		this.proceessInstanceId = proceessInstanceId;
	}

	public java.lang.String getMongoDocID() {
		return this.mongoDocID;
	}

	public void setMongoDocID(java.lang.String mongoDocID) {
		this.mongoDocID = mongoDocID;
	}

	public java.lang.String getProduct() {
		return this.product;
	}

	public void setProduct(java.lang.String product) {
		this.product = product;
	}

	public java.lang.String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(java.lang.String agentId) {
		this.agentId = agentId;
	}

	public java.lang.Integer getCoem() {
		return this.coem;
	}

	public void setCoem(java.lang.Integer coem) {
		this.coem = coem;
	}

	public java.lang.String getCoExcl() {
		return this.coExcl;
	}

	public void setCoExcl(java.lang.String coExcl) {
		this.coExcl = coExcl;
	}

	public java.lang.Integer getLevel() {
		return this.level;
	}

	public void setLevel(java.lang.Integer level) {
		this.level = level;
	}

	public java.lang.String getLastUser() {
		return this.lastUser;
	}

	public void setLastUser(java.lang.String lastUser) {
		this.lastUser = lastUser;
	}

	public java.lang.String getFinfoId() {
		return this.finfoId;
	}

	public void setFinfoId(java.lang.String finfoId) {
		this.finfoId = finfoId;
	}

	public java.lang.Double getPremium() {
		return this.premium;
	}

	public void setPremium(java.lang.Double premium) {
		this.premium = premium;
	}

	public java.lang.String getDecision() {
		return this.decision;
	}

	public void setDecision(java.lang.String decision) {
		this.decision = decision;
	}

	public java.lang.Integer getCount() {
		return this.count;
	}

	public void setCount(java.lang.Integer count) {
		this.count = count;
	}

	public java.lang.String getChannel() {
		return this.channel;
	}

	public void setChannel(java.lang.String channel) {
		this.channel = channel;
	}

	public CaseData(java.lang.String clientId, java.lang.String role,
			java.lang.Double sumAssured, java.lang.String applicationNo,
			java.lang.Integer priority, java.lang.Long proceessInstanceId,
			java.lang.String mongoDocID, java.lang.String product,
			java.lang.String agentId, java.lang.Integer coem,
			java.lang.String coExcl, java.lang.Integer level,
			java.lang.String lastUser, java.lang.String finfoId,
			java.lang.Double premium, java.lang.String decision,
			java.lang.Integer count, java.lang.String channel) {
		this.clientId = clientId;
		this.role = role;
		this.sumAssured = sumAssured;
		this.applicationNo = applicationNo;
		this.priority = priority;
		this.proceessInstanceId = proceessInstanceId;
		this.mongoDocID = mongoDocID;
		this.product = product;
		this.agentId = agentId;
		this.coem = coem;
		this.coExcl = coExcl;
		this.level = level;
		this.lastUser = lastUser;
		this.finfoId = finfoId;
		this.premium = premium;
		this.decision = decision;
		this.count = count;
		this.channel = channel;
	}

}